### PR TITLE
fix: improve performance and memory management

### LINKED ISSUE #67: [Bug]: cpu utilisation increasing rapidly with time
### Kong Version

3.7.1

### Plugin Version

0.2.1

### On which environment your Kong instance is running?

Kubernetes

### Plugin Configuration

apiVersion: configuration.konghq.com/v1
config:
  agent_host: datadog.ns.svc.cluster.local
  environment: prod
  service_name: kong
  static_tags:
  - name: service
    value: service-name
  trace_agent_port: 8126
kind: KongPlugin

### What happened?

We started with this latest version of the plugin, seems like this caused CPU spike over time.
Please see the screenshot below, this caused increased latencies in the server causing application timeouts eventually and we had setup a restart cron every 30 minutes as a workaround. So, if you see the graph it rapidly increases and after 30 min it drops down. We tried different plugins and finally found this opentelemetry plugin as the savior here. After switching apm to opentelemetry, the cpu usage stabilised. Please look into this. Below graph shows CPU usage with ddtrace and opentelemetry plugins.
Image

### LINKED ISSUE #75: [Bug]: memory leak in proxy container when using ddtrace plugin
### Kong Version

3.4.2 (LTS)

### Plugin Version

0.2.2

### On which environment your Kong instance is running?

Kubernetes

### Plugin Configuration

```yaml
We use defaults and set ENV variables for `DD_*`, which works correctly.
```

### What happened?

After we enable `ddtrace` plugin, memory of `proxy` container starts growing until it's OOMKilled. Without `ddtrace` plugin, we are OK with ~280MB of memory. I've tried setting higher limits up to 1G without a success.

### PR DESCRIPTION
**Pull request by dmehala**
# Description
This PR improves the performance and memory usage of the `kong-plugin-ddtrace` plugin by introducing optimizations in key areas. The changes aim to reduce memory overhead, enhance execution efficiency, and improve overall stability.  

### Changes
  - Update README to mention the lowest version of Kong Gateway supported.
  - Use Kong Queue API for sending traces to the Agent instead of our custom solution with NGINX timer.
  - Remove anonymous function in `pcall`.
  - Use an higher clock precision.
  - Add integration tests.
  - Unit test the schema.

Resolves #75 
Resolves #67

### CODE REVIEW

File: kong/plugins/ddtrace/handler.lua [hunk 1]
```diff
@@ -21,115 +22,42 @@ local DatadogTraceHandler = {
...
-    end
-end
-
 local function expose_tracing_variables(span)
     -- Expose traceID and parentID for other plugin to consume and also set an NGINX variable
     -- that can be use for in `log_format` directive for correlation with logs.
     local trace_id = btohex(span.trace_id.high or 0, 16) .. btohex(span.trace_id.low, 16)
     local span_id = btohex(span.span_id, 16)
+    -- local trace_id = btohex(span.trace_id.high or 0, 16) .. btohex(span.trace_id.low, 16)
+    -- local span_id = btohex(span.span_id, 16)
```
Comment (dmehala) [inline kong/plugins/ddtrace/handler.lua:53]: - [ ] remove

File: kong/plugins/ddtrace/handler.lua [hunk 2]
```diff
@@ -244,256 +171,243 @@ local function configure(conf)
...
+        request_span:set_tag("kong.database", kong.configuration.database)
     end
 
-    function DatadogTraceHandler:header_filter(conf) -- luacheck: ignore 212
-        local ok, message = pcall(function()
-            self:header_filter_p(conf)
-        end)
-        if not ok then
-            kong.log.err("tracing error in DatadogTraceHandler:header_filter: " .. message)
+    local static_tags = conf and conf.static_tags or nil
```
Comment (dmehala) [inline kong/plugins/ddtrace/handler.lua:236]:
```suggestion
    local static_tags = conf.static_tags
```

File: README.md [hunk 3]
```diff
@@ -1,23 +1,36 @@
...
+- **Configurable**: Supports a wide range of configuration options to tailor tracing to your specific needs.
+- **Compatibility**: Works with various Kong deployment environments, including Kubernetes.
 
-## Installation
+## Getting Started
 
-This plugin can be installed using `luarocks`.
+> [!IMPORTANT]
+> This plugin is compatible with Kong Gateway `v3.5+`.
+> For older version of Kong, please use [v0.2.2](https://github.com/DataDog/kong-plugin-ddtrace/releases/tag/v0.2.2) or older versions.
```
Comment (Kyslik) [inline README.md:18]: Please note that Kong 3.4 is LTS - https://docs.konghq.com/gateway/latest/support-policy/#supported-versions, `0.2.2` has possible memory leak as reported https://github.com/DataDog/kong-plugin-ddtrace/issues/75.

Comment (dmehala) [reply README.md:18]: Thanks for bringing this up! In theory, the plugin should work with `v3.4`. However, during my testing, I found that the new `configure` handler isn't being called, which prevents the module from functioning properly. This contradicts [Kong's documentation](https://docs.konghq.com/gateway/latest/plugin-development/custom-logic/#available-contexts), which states:  

> The configure handler was added in Kong 3.5 and backported to 3.4 LTS. We are currently looking for feedback on this new phase, and there is a slight possibility that its signature might change in the future.  

I need to check with the Kong team to confirm whether the `configure` handler was actually backported and from which specific version. Otherwise, I’d have to call `configure` on every request, which could impact performance. Rest assured, the next version—featuring performance and memory improvements—will be fully compatible with Kong 3.4.

**Comment by dmehala** [comment]
Bump @dubloom @pablomartinezbernardo

**Comment by dubloom** [comment]
👀

File: spec/01-unit-tests/05_utils_spec.lua
Comment (pablomartinezbernardo) [inline spec/01-unit-tests/05_utils_spec.lua:1]: pickiest of nits: missing 04 after the split in folders

File: kong/plugins/ddtrace/handler.lua [hunk 4]
```diff
@@ -244,256 +171,243 @@ local function configure(conf)
...
+    span:finish(now)
+end
+
+local function log(conf)
+    local now = time_ns() * 1LL
+    local ngx_ctx = ngx.ctx
+
+    local ctx = kong.ctx.plugin
+    if ctx.request_span == nil then
+        error("request span is missing during the log phase")
```
Comment (pablomartinezbernardo) [inline kong/plugins/ddtrace/handler.lua:339]: What are the consequences of `error`ing here? Is the error handled gracefully by kong?

File: kong/plugins/ddtrace/agent_writer.lua [hunk 5]
```diff
@@ -1,21 +1,34 @@
...
 }
 
+local queue_conf = {
+    name = "ddtrace",
+    log_tag = "ddtrace.writer",
+    max_batch_size = 100,
+    max_coalescing_delay = 2,
+    max_entries = 10000,
+    -- Intake max payload allowed is 5MiB
+    max_bytes = 5 * 8388608,
```
Comment (pablomartinezbernardo) [inline kong/plugins/ddtrace/agent_writer.lua:18]:
```suggestion
    max_bytes = 5 * 1024 * 1024,
```

`5 * 8388608` bytes is 40MiB (`5 * 8388608` bits would actually be  5MiB)

File: kong/plugins/ddtrace/handler.lua (hunk 4 above)
Comment (dmehala) [reply kong/plugins/ddtrace/handler.lua:339]: `error` is like an exception raised that is catched by `pcall`. More details here: https://www.lua.org/pil/8.5.html

File: README.md [hunk 6]
```diff
@@ -1,23 +1,36 @@
...
+- **Real-Time Monitoring**: Integrate with Datadog to monitor API performance and diagnose issues in real-time.
+- **Configurable**: Supports a wide range of configuration options to tailor tracing to your specific needs.
+- **Compatibility**: Works with various Kong deployment environments, including Kubernetes.
 
-## Installation
+## Getting Started
 
-This plugin can be installed using `luarocks`.
+> [!IMPORTANT]
+> This plugin is compatible with Kong Gateway `v3.5+`.
```
[the remark this answers is not in the document]
Comment (dmehala) [reply README.md:17]: Until I can confirm with Kong's team kong `v3.4` support the `configuration` handler.  The current wording is correct. I'll create a subsequent PR once I get the confirmation.

**Review by dubloom — APPROVED** [review]
With my little understanding of kong, it looks good to me.
Two questions though:
- why are we not doing any checks on injection_propagation_styles on ddtrace_conf ? Does something guarantee it will not be null ? 
- why does the sending traces to datadog part is in a log function ? That does not really make sense

File: kong/plugins/ddtrace/handler.lua (hunk 1 above)
Comment (dmehala) [inline kong/plugins/ddtrace/handler.lua:53]:
```suggestion
```

File: README.md (hunk 3 above)
Comment (Kyslik) [reply README.md:18]: Yes, anything 3.4 will work for us. Thank you.
