### PR TITLE
fix: resolves environment variable using Lua builtin

### LINKED ISSUE #53: [Bug]: Warning logs on environment read in latest version
### Kong Version

3.6.1

### Plugin Version

0.2.0-1

### On which environment your Kong instance is running?

ECS

### Plugin Configuration

```yaml
_format_version: "3.0"

_info:
  defaults: {}
  select_tags:
    - ddtrace

plugins:
  - name: ddtrace
    tags:
      - ddtrace
    config:
      service_name: my-api-gateway
      environment: production
      static_tags:
        - name: app
          value: my-api-gateway
```

### What happened?

Within this latest version, I'm getting several warning logs from the plugin about errors on reading the env configs from a vault: 
image

```
2024/04/16 16:33:48 [warn] 1363#0: *2487 [kong] vault.lua:1255 could not retrieve value for reference {vault://env/DD_TRACE_PROPAGATION_STYLE_EXTRACT} (could not get value from external vault (no value found)), context: ngx.timer
``` 
I don't even have a vault configured within this Kong.

This is not impacting the availability of the Kong Gateway, but it's a very verbose log that's being triggered all the time.

### PR DESCRIPTION
**Pull request by dmehala**
# Description
Replaces the use of `kong.vault` with `os.getenv` for resolving environment variables. The previous approach using `kong.vault` often resulted in excessively verbose logs when environment variables were missing.  

### Changes:
- Replaced `kong.vault` with `os.getenv` for retrieving environment variables.  
- Added integration tests to ensure correct behavior.  
- Encoded the tracer configuration in JSON within the Datadog log for better readability and consistency.  

Resolves #53

### CODE REVIEW

**Review by pablomartinezbernardo — APPROVED** [review]

**Comment by dubloom** [comment]
I'll take a look tomorrow !

**Review by dubloom — APPROVED** [review]
LGTM

File: kong/plugins/ddtrace/handler.lua [hunk 1]
```diff
@@ -49,6 +61,8 @@ local function expose_tracing_variables(span)
     -- that can be use for in `log_format` directive for correlation with logs.
     local trace_id = btohex(span.trace_id.high or 0, 16) .. btohex(span.trace_id.low, 16)
     local span_id = btohex(span.span_id, 16)
+    -- local trace_id = btohex(span.trace_id.high or 0, 16) .. btohex(span.trace_id.low, 16)
+    -- local span_id = btohex(span.span_id, 16)
```
Comment (dmehala) [inline kong/plugins/ddtrace/handler.lua:65]:
```suggestion
```
